all:
  children:

    k8s_nodes:
      hosts:
        controlplane:
          ansible_host: 192.168.2.70
        node01:
          ansible_host: 192.168.2.71
        jmedia:
          ansible_host: 192.168.2.50

    swarm_nodes:
      hosts:
        node02:
          ansible_host: 192.168.2.72

  vars:
    ansible_user: ansible